### ISSUE TITLE
提案: エイリアスパターン

### ISSUE THREAD

**Issue by tenzyu** [tenzyu/simple-controller#8]
# 目標
より直感的 かつ より重複しないエイリアスのパターン化

## 現在のままでは重複するエイリアス
- ?channel rename -> ?cr
- ?category rename -> ?cr
- ?reaction clear -> ?rc
- ?role color -> ?rc

## 新しいエイリアスパターンの提案
※メンション化防止に半角スペース入り

### ex1) ?channel rename
@ group(aliases=["ch"]) かつ @ channel.command(aliases=["r"])
\>>> ?ch r `name`

### ex2) ?category rename
@ group(aliases=["cat"]) かつ @ channel.command(aliases=["r"])
\>>> ?cat r `name`

## このパターンのメリット
- 現在と比べてコードが少なくなる
- より直感的
- より重複されない

## ?ca ではなくて ?cat である理由
そのほうが一般的でありそうだから。
https://ja.wikipedia.org/wiki/CAT
https://e-words.jp/w/カテゴリ.html
https://qiita.com/mrd-takahashi/items/e1099e12bac388d0a9cd

**Comment by AttoCat** [comment]
catについては、確かに一般的かもしれないけど2文字目までを取る　のルールのほうがわかりやすそうかなーとは思った
複数指定できるので、ca も指定したいかも

**Comment by tenzyu** [comment]
`?ca` 了解、もう全て書き換えていい？

**Comment by AttoCat** [comment]
大丈夫だと思う！
まぁカスタムプレフィックスコマンドについては2文字目までをとる　ルールじゃないけどね。
あんまり複雑にルール決めてもあれだし、適宜決めてこ
